export const themeData = [
{
    key: 0,
    themeName1: "Rose",
    themeName2: "Neutral",
    colorLight: "neutral-50",
    colorLightHex: "#fafafa",
    colorLightAccent: "rose-100",
    colorLightAccentHex: "#FEE2E2",
    colorMediumAccent: "rose-400",
    colorMediumAccentHex: "#F87171",
    colorMedium: "rose-500",
    colorMediumHex: "#EF4444",
    colorText: "rose-700",
    colorTextHex: "#B91C1C",
    
},
{
    key: 2,
    themeName1: "Pink",
    themeName2: "Neutral",
    colorLight: "neutral-50",
    colorLightHex: "#fafafa",
    colorLightAccent: "pink-100",
    colorLightAccentHex: "#fce7f3",
    colorMediumAccent: "pink-400",
    colorMediumAccentHex: "#f472b6",
    colorMedium: "pink-500",
    colorMediumHex: "#ec4899",
    colorText: "pink-700",
    colorTextHex: "#be185d",
},
{
    key: 3,
    themeName1: "Fuchsia",
    themeName2: "Neutral",
    colorLight: "neutral-50",
    colorLightHex: "#fafafa",
    colorLightAccent: "fuchsia-100",
    colorLightAccentHex: "#fae8ff",
    colorMediumAccent: "fuchsia-400",
    colorMediumAccentHex: "#e879f9",
    colorMedium: "fuchsia-500",
    colorMediumHex: "#d946ef",
    colorText: "fuchsia-700",
    colorTextHex: "#a21caf",
},
{
    key: 4,
    themeName1: "Purple",
    themeName2: "Neutral",
    colorLight: "neutral-50",
    colorLightHex: "#fafafa",
    colorLightAccent: "purple-100",
    colorLightAccentHex: "#f3e8ff",
    colorMediumAccent: "purple-400",
    colorMediumAccentHex: "#c084fc",
    colorMedium: "purple-500",
    colorMediumHex: "#a855f7",
    colorText: "purple-700",
    colorTextHex: "#7e22ce",
},
{
    key: 5,
    themeName1: "Violet",
    themeName2: "Neutral",
    colorLight: "neutral-50",
    colorLightHex: "#fafafa",
    colorLightAccent: "violet-100",
    colorLightAccentHex: "#ede9fe",
    colorMediumAccent: "violet-400",
    colorMediumAccentHex: "#a78bfa",
    colorMedium: "violet-500",
    colorMediumHex: "#8b5cf6",
    colorText: "violet-700",
    colorTextHex: "#6d28d9",
},
{
    key: 6,
    themeName1: "Indigo",
    themeName2: "Neutral",
    colorLight: "neutral-50",
    colorLightHex: "#fafafa",
    colorLightAccent: "indigo-100",
    colorLightAccentHex: "#e0e7ff",
    colorMediumAccent: "indigo-400",
    colorMediumAccentHex: "#818cf8",
    colorMedium: "indigo-500",
    colorMediumHex: "#6366f1",
    colorText: "indigo-700",
    colorTextHex: "#4338ca",
},
{
    key: 7,
    themeName1: "Blue",
    themeName2: "Neutral",
    colorLight: "neutral-50",
    colorLightHex: "#fafafa",
    colorLightAccent: "blue-100",
    colorLightAccentHex: "#dbeafe",
    colorMediumAccent: "blue-400",
    colorMediumAccentHex: "#60a5fa",
    colorMedium: "blue-500",
    colorMediumHex: "#3b82f6",
    colorText: "blue-700",
    colorTextHex: "#1d4ed8",
},
{
    key: 7,
    themeName1: "Sky",
    themeName2: "Neutral",
    colorLight: "neutral-50",
    colorLightHex: "#fafafa",
    colorLightAccent: "sky-100",
    colorLightAccentHex: "#e0f2fe",
    colorMediumAccent: "sky-400",
    colorMediumAccentHex: "#38bdf8",
    colorMedium: "sky-500",
    colorMediumHex: "#0ea5e9",
    colorText: "sky-700",
    colorTextHex: "#0369a1",
},
{
    key: 8,
    themeName1: "Cyan",
    themeName2: "Neutral",
    colorLight: "neutral-50",
    colorLightHex: "#fafafa",
    colorLightAccent: "cyan-100",
    colorLightAccentHex: "#cffafe",
    colorMediumAccent: "cyan-400",
    colorMediumAccentHex: "#22d3ee",
    colorMedium: "cyan-500",
    colorMediumHex: "#06b6d4",
    colorText: "cyan-700",
    colorTextHex: "#0e7490",
},
{
    key: 9,
    themeName1: "Teal",
    themeName2: "Neutral",
    colorLight: "neutral-50",
    colorLightHex: "#fafafa",
    colorLightAccent: "teal-100",
    colorLightAccentHex: "#ccfbf1",
    colorMediumAccent: "teal-400",
    colorMediumAccentHex: "#2dd4bf",
    colorMedium: "teal-500",
    colorMediumHex: "#14b8a6",
    colorText: "teal-700",
    colorTextHex: "#0f766e",
},
{
    key: 10,
    themeName1: "Emerald",
    themeName2: "Neutral",
    colorLight: "neutral-50",
    colorLightHex: "#fafafa",
    colorLightAccent: "emerald-100",
    colorLightAccentHex: "#d1fae5",
    colorMediumAccent: "emerald-400",
    colorMediumAccentHex: "#34d399",
    colorMedium: "emerald-500",
    colorMediumHex: "#10b981",
    colorText: "emerald-700",
    colorTextHex: "#047857",
},
{
    key: 11,
    themeName1: "Green",
    themeName2: "Neutral",
    colorLight: "neutral-50",
    colorLightHex: "#fafafa",
    colorLightAccent: "green-100",
    colorLightAccentHex: "#dcfce7",
    colorMediumAccent: "green-400",
    colorMediumAccentHex: "#4ade80",
    colorMedium: "green-500",
    colorMediumHex: "#22c55e",
    colorText: "green-700",
    colorTextHex: "#15803d",
},
{
    key: 12,
    themeName1: "Lime",
    themeName2: "Neutral",
    colorLight: "neutral-50",
    colorLightHex: "#fafafa",
    colorLightAccent: "lime-100",
    colorLightAccentHex: "#ecfccb",
    colorMediumAccent: "lime-400",
    colorMediumAccentHex: "#a3e635",
    colorMedium: "lime-500",
    colorMediumHex: "#84cc16",
    colorText: "lime-700",
    colorTextHex: "#4d7c0f",
},
{
    key: 13,
    themeName1: "Yellow",
    themeName2: "Neutral",
    colorLight: "neutral-50",
    colorLightHex: "#fafafa",
    colorLightAccent: "yellow-100",
    colorLightAccentHex: "#fef9c3",
    colorMediumAccent: "yellow-400",
    colorMediumAccentHex: "#facc15",
    colorMedium: "yellow-500",
    colorMediumHex: "#eab308",
    colorText: "yellow-700",
    colorTextHex: "#a16207",
},
{
    key: 14,
    themeName1: "Amber",
    themeName2: "Neutral",
    colorLight: "neutral-50",
    colorLightHex: "#fafafa",
    colorLightAccent: "amber-100",
    colorLightAccentHex: "#fef3c7",
    colorMediumAccent: "amber-400",
    colorMediumAccentHex: "#fbbf24",
    colorMedium: "amber-500",
    colorMediumHex: "#f59e0b",
    colorText: "amber-700",
    colorTextHex: "#b45309",
},
{
    key: 15,
    themeName1: "Orange",
    themeName2: "Neutral",
    colorLight: "neutral-50",
    colorLightHex: "#fafafa",
    colorLightAccent: "orange-100",
    colorLightAccentHex: "#ffedd5",
    colorMediumAccent: "orange-400",
    colorMediumAccentHex: "#fb923c",
    colorMedium: "orange-500",
    colorMediumHex: "#f97316",
    colorText: "orange-700",
    colorTextHex: "#c2410c",
},
{
    key: 16,
    themeName1: "Red",
    themeName2: "Neutral",
    colorLight: "neutral-50",
    colorLightHex: "#fafafa",
    colorLightAccent: "red-100",
    colorLightAccentHex: "#fee2e2",
    colorMediumAccent: "red-400",
    colorMediumAccentHex: "#f87171",
    colorMedium: "red-500",
    colorMediumHex: "#ef4444",
    colorText: "red-700",
    colorTextHex: "#b91c1c",
},
]