export const themeData = [
{
    key: 0,
    themeName1: "Rose",
    themeName2: "Stone",
    colorLight: "stone-50",
    colorLightHex: "#f8fafc",
    colorLightAccent: "rose-100",
    colorLightAccentHex: "#FEE2E2",
    colorMediumAccent: "rose-400",
    colorMediumAccentHex: "#F87171",
    colorMedium: "rose-500",
    colorMediumHex: "#EF4444",
    colorText: "rose-700",
    colorTextHex: "#B91C1C",
    
},
{
    key: 2,
    themeName1: "Pink",
    themeName2: "Stone",
    colorLight: "stone-50",
    colorLightHex: "#f8fafc",
    colorLightAccent: "pink-100",
    colorLightAccentHex: "#fce7f3",
    colorMediumAccent: "pink-400",
    colorMediumAccentHex: "#f472b6",
    colorMedium: "pink-500",
    colorMediumHex: "#ec4899",
    colorText: "pink-700",
    colorTextHex: "#be185d",
},
{
    key: 3,
    themeName1: "Fuchsia",
    themeName2: "Stone",
    colorLight: "stone-50",
    colorLightHex: "#f8fafc",
    colorLightAccent: "fuchsia-100",
    colorLightAccentHex: "#fae8ff",
    colorMediumAccent: "fuchsia-400",
    colorMediumAccentHex: "#e879f9",
    colorMedium: "fuchsia-500",
    colorMediumHex: "#d946ef",
    colorText: "fuchsia-700",
    colorTextHex: "#a21caf",
},
]