export const themeData = [
{
    key: 0,
    themeName1: "Rose",
    themeName2: "Stone",
    colorLight: "stone-50",
    colorLightHex: "#f8fafc",
    colorLightAccent: "rose-100",
    colorLightAccentHex: "#FEE2E2",
    colorMediumAccent: "rose-400",
    colorMediumAccentHex: "#F87171",
    colorMedium: "rose-500",
    colorMediumHex: "#EF4444",
    colorText: "rose-700",
    colorTextHex: "#B91C1C",
    
},
{
    key: 2,
    themeName1: "Pink",
    themeName2: "Stone",
    colorLight: "stone-50",
    colorLightHex: "#f8fafc",
    colorLightAccent: "pink-100",
    colorLightAccentHex: "#fce7f3",
    colorMediumAccent: "pink-400",
    colorMediumAccentHex: "#f472b6",
    colorMedium: "pink-500",
    colorMediumHex: "#ec4899",
    colorText: "pink-700",
    colorTextHex: "#be185d",
},
{
    key: 3,
    themeName1: "Fuchsia",
    themeName2: "Stone",
    colorLight: "stone-50",
    colorLightHex: "#f8fafc",
    colorLightAccent: "fuchsia-100",
    colorLightAccentHex: "#fae8ff",
    colorMediumAccent: "fuchsia-400",
    colorMediumAccentHex: "#e879f9",
    colorMedium: "fuchsia-500",
    colorMediumHex: "#d946ef",
    colorText: "fuchsia-700",
    colorTextHex: "#a21caf",
},
{
    key: 4,
    themeName1: "Purple",
    themeName2: "Stone",
    colorLight: "stone-50",
    colorLightHex: "#f8fafc",
    colorLightAccent: "purple-100",
    colorLightAccentHex: "#f3e8ff",
    colorMediumAccent: "purple-400",
    colorMediumAccentHex: "#c084fc",
    colorMedium: "purple-500",
    colorMediumHex: "#a855f7",
    colorText: "purple-700",
    colorTextHex: "#7e22ce",
},
{
    key: 5,
    themeName1: "Violet",
    themeName2: "Stone",
    colorLight: "stone-50",
    colorLightHex: "#f8fafc",
    colorLightAccent: "violet-100",
    colorLightAccentHex: "#ede9fe",
    colorMediumAccent: "violet-400",
    colorMediumAccentHex: "#a78bfa",
    colorMedium: "violet-500",
    colorMediumHex: "#8b5cf6",
    colorText: "violet-700",
    colorTextHex: "#6d28d9",
},
{
    key: 6,
    themeName1: "Indigo",
    themeName2: "Stone",
    colorLight: "stone-50",
    colorLightHex: "#f8fafc",
    colorLightAccent: "indigo-100",
    colorLightAccentHex: "#e0e7ff",
    colorMediumAccent: "indigo-400",
    colorMediumAccentHex: "#818cf8",
    colorMedium: "indigo-500",
    colorMediumHex: "#6366f1",
    colorText: "indigo-700",
    colorTextHex: "#4338ca",
},
{
    key: 7,
    themeName1: "Blue",
    themeName2: "Stone",
    colorLight: "stone-50",
    colorLightHex: "#f8fafc",
    colorLightAccent: "blue-100",
    colorLightAccentHex: "#dbeafe",
    colorMediumAccent: "blue-400",
    colorMediumAccentHex: "#60a5fa",
    colorMedium: "blue-500",
    colorMediumHex: "#3b82f6",
    colorText: "blue-700",
    colorTextHex: "#1d4ed8",
},
]